<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/favicon.ico' rel='icon' type='image/x-icon'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link color='#2B90D9' href='/mask-icon.svg' rel='mask-icon'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>killmi.st
 - killmi.st</title>
<link rel="stylesheet" media="all" href="/assets/application-b7d32e1a05cf50241f3074c5038f423a251e081f210ad7fdc238029d85f502f2.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="fnAXwGLGtBxgIiYARromIyqTBg+EbKFJTbM50FzBPNUFE1Z8nY0j+MVtM8ygvVuny+BIfMC/GzuYqOMIw2C8dA==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>killmi.st</h2>
<p>キルミストのキルミストによるキルミストのためのマストドンインスタンスです。</p>
</div>
<div class='information-board'>
<div class='section'>
<span>Home to</span>
<strong>2</strong>
<span>users</span>
</div>
<div class='section'>
<span>Who authored</span>
<strong>3</strong>
<span>statuses</span>
</div>
<div class='section'>
<span>Connected to</span>
<strong>1</strong>
<span>other instances</span>
</div>
</div>
<div class='panel'>キルミスト向けのインスタンスです
投稿内容はキルミーに限らず特に制限はありませんが、R-18コンテンツにはNSFWつけてください</div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>Contact</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="https://media.killmi.st/mastodon/accounts/avatars/000/000/001/original/26aa9042298a98ca.png" alt="26aa9042298a98ca" /></div>
<div class='name'>
<a href="https://killmi.st/@aoisensi"><span class='display_name emojify'>aoisensi</span>
<span class='username'>@aoisensi</span>
</a></div>
</div>
<div class='contact-email'>
Business e-mail:
<strong>aoiseni@outlook.jp</strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Links</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></li>
</ul>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Version</div>
<div class='panel-body'>
<strong>1.3.2</strong>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
