<!DOCTYPE html>
<html lang='ja'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/favicon.ico' rel='icon' type='image/x-icon'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link color='#2B90D9' href='/mask-icon.svg' rel='mask-icon'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>lovelive-anime.tk
 - Mastodon With LoveLive!</title>
<link rel="stylesheet" media="all" href="/assets/application-b7d32e1a05cf50241f3074c5038f423a251e081f210ad7fdc238029d85f502f2.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="lTkEL3NVXV25E4UiOqRDoe0G6jmAoRGGozWmY3SlrA6tvjN1GOCq3lEfh1EvZLyKcj5wislOYshYCAbHzpMafg==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>lovelive-anime.tk</h2>
<p>ラブライブ！のファンコミュニティです。<br>
μ&#39;sic Forever!

<h3>登録確認メールについて</h3>
<p>登録確認メールが届かない場合、迷惑メールフォルダに入っていることがあります。<br>
5分経過して届かない場合は、お手数ですが一度ご確認ください。<br>
それでも登録できない場合、下記のお問い合わせからご連絡いただければ手動で対応致します。</p>

<h3>投稿の注意事項</h3>
<p>犯罪予告や他者の権利を侵害する投稿などは受け付けておりません。<br>これらの投稿は予告なく削除及び投稿者アカウントの停止等の措置を行う場合があります。</p>
<p>R-15を超えるような画像はアップロード後「NSFW」ボタンを押すことでタイムライン上での表示にワンクッション置くことが出来ます。（いわゆる閲覧注意）<font color="red">※強く推奨します</font></p>
<p>以上のルールは当インスタンス独自のものです。他インスタンスを利用される場合はそのインスタンスのルールに従ってください。</p>

<h3>お問い合わせ</h3>
<p>Mastodon内 : <a href="https://lovelive-anime.tk/@niru_live">@niru_live</a><br>またはメール : notifications@lovelive-anime.tk</p></p>
</div>
<div class='information-board'>
<div class='section'>
<span>ユーザー数</span>
<strong>268</strong>
<span>人</span>
</div>
<div class='section'>
<span>トゥート数</span>
<strong>2,035</strong>
<span>トゥート</span>
</div>
<div class='section'>
<span>接続中</span>
<strong>222</strong>
<span>個のインスタンス</span>
</div>
</div>
<div class='panel'>お問い合わせは「notifications@lovelive-anime.tk」へ。</div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>連絡先</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="/system/accounts/avatars/000/000/001/original/4fc2df0d95f0a052.png?1492141651" alt="4fc2df0d95f0a052" /></div>
<div class='name'>
<a href="https://lovelive-anime.tk/@niru_live"><span class='display_name emojify'>ニール</span>
<span class='username'>@niru_live</span>
</a></div>
</div>
<div class='contact-email'>
ビジネスメールアドレス:
<strong>notifications@lovelive-anime.tk</strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>リンク</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">参加する</a></li>
<li><a href="/auth/sign_in">ログイン</a></li>
<li><a href="/terms">プライバシーポリシー</a></li>
<li><a href="https://github.com/tootsuite/mastodon">ソースコード</a></li>
</ul>
</div>
</div>

<div class='panel'>
<div class='panel-header'>バージョン</div>
<div class='panel-body'>
<strong>1.3.2</strong>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
