<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>mastodon.in.ua
 - Mastodon:UA</title>
<link rel="stylesheet" media="all" href="/assets/application-df75cb7ffdfd49c4b4a90c2d74768116b98039e26a55870bf47b737c2ad5d9b2.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="ddZOxewVUYt2BXRIZvDEtlIGGLLbzcKqC4HZ4P2n7s5e1bcru7s3lHIbIDhCoGeRHEjxEYQiHVGYsr7LvinL+g==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>mastodon.in.ua</h2>
<p>One of the first Ukrainian based mastodon instance.</p>
</div>
<div class='information-board'>
<div class='section'>
<span>Home to</span>
<strong>13</strong>
<span>users</span>
</div>
<div class='section'>
<span>Who authored</span>
<strong>7</strong>
<span>statuses</span>
</div>
<div class='section'>
<span>Connected to</span>
<strong>149</strong>
<span>other instances</span>
</div>
</div>
<div class='panel'>We'll be very happy to welcome you on board!


We support freedom of speech, and we will not block instances or users unless there is a good reason.</div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>Contact</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="/system/accounts/avatars/000/000/001/original/f5dadf997fda40c4.jpeg?1492604597" alt="F5dadf997fda40c4" /></div>
<div class='name'>
<a href="https://mastodon.in.ua/@h1kkan"><span class='display_name emojify'>h1kkan ✅</span>
<span class='username'>@h1kkan</span>
</a></div>
</div>
<div class='contact-email'>
Business e-mail:
<strong>staff@mastodon.in.ua</strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Links</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></li>
</ul>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
