<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/favicon.ico' rel='icon' type='image/x-icon'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link color='#2B90D9' href='/mask-icon.svg' rel='mask-icon'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>mastodon.103.ms
 - mastodon.103.ms</title>
<link rel="stylesheet" media="all" href="/assets/application-b7d32e1a05cf50241f3074c5038f423a251e081f210ad7fdc238029d85f502f2.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="o5ARHZ/jSLNZz6/kvr/WlR9bHyYHjeYBkxmL6M+X0tdbAyHtoooznnyN13b+8KZlBhilckGnNIF5wukhpzElug==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>mastodon.103.ms</h2>
</div>
<div class='information-board'>
<div class='section'>
<span>Home to</span>
<strong>3</strong>
<span>users</span>
</div>
<div class='section'>
<span>Who authored</span>
<strong>18</strong>
<span>statuses</span>
</div>
<div class='section'>
<span>Connected to</span>
<strong>280</strong>
<span>other instances</span>
</div>
</div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>Contact</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="/system/accounts/avatars/000/000/001/original/6f8929e35e36df35.jpg?1492273200" alt="6f8929e35e36df35" /></div>
<div class='name'>
<a href="https://mastodon.103.ms/@friendD"><span class='display_name emojify'>friendD</span>
<span class='username'>@friendD</span>
</a></div>
</div>
<div class='contact-email'>
Business e-mail:
<strong>admin@mastodon.103.ms</strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Links</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></li>
</ul>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Version</div>
<div class='panel-body'>
<strong>1.3.2</strong>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
