<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link color='#2B90D9' href='/mask-icon.svg' rel='mask-icon'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>mastodon.machique.st - Mastodon for まちクエスト</title>
<link rel="stylesheet" media="all" href="/assets/application-b5708bb73cded1fb0546a285175cbf46a32654dcecbbf576bb9ed5630fc8089b.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="+Baj0iTKy87dfgyj9t8OVHzo2EwTXgh0pKyhA2Vghlf7GWJBXwbRzywWpaUUJf0ytIDBZuHozzpgw51MNDzJ2g==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>mastodon.machique.st</h2>
<p>クイズを解きながら街歩きが楽しめるスマートフォン向けウォークラリー「<a href="http://machique.st">まちクエスト</a>」ユーザーのためのMastodonインスタンスです。まちクエユーザーでなくても、ポケモンGo、ジオキャッシングといった位置情報ゲーム、位置情報アプリに興味がある方にご利用いただけます。</p>
</div>
<div class='information-board'>
<div class='section'>
<span>Home to</span>
<strong>39</strong>
<span>users</span>
</div>
<div class='section'>
<span>Who authored</span>
<strong>176</strong>
<span>statuses</span>
</div>
<div class='section'>
<span>Connected to</span>
<strong>180</strong>
<span>other instances</span>
</div>
</div>
<div class='panel'>クイズを解きながら街歩きが楽しめるスマートフォン向けウォークラリー「<a href="http://machique.st">まちクエスト</a>」ユーザーのためのMastodonインスタンスです。まちクエユーザーでなくても、ポケモンGo、ジオキャッシングといった位置情報ゲーム、位置情報アプリに興味がある方にご利用いただけます。</div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>Contact</div>
<div class='panel-body'>
<div class='contact-email'>
Business e-mail:
<strong>webmaster@machique.st</strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Links</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></li>
</ul>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
