<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link color='#2B90D9' href='/mask-icon.svg' rel='mask-icon'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>social.weho.st
 - social.weho.st</title>
<link rel="stylesheet" media="all" href="/assets/application-9f05ad922cfe8101e88e15d98470914c52e9abd25d84c6dbd270a7ae47ced160.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="nXM4yYqLbpYMBDsu0Qxu2utsEJ/KaSuCHSKFQmRXNPCltAec/Yv3qAxBUJrNcPZ1dHpUz+mGtC6jAe/Omd93Rw==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>social.weho.st</h2>
<p>This is an instance of mastodon that runs on the https://weho.st platform.

weho.st is a non-profit internet service provider based in Amsterdam in the Netherlands.</p>
</div>
<div class='information-board'>
<div class='section'>
<span>Home to</span>
<strong>79</strong>
<span>users</span>
</div>
<div class='section'>
<span>Who authored</span>
<strong>2,633</strong>
<span>statuses</span>
</div>
<div class='section'>
<span>Connected to</span>
<strong>630</strong>
<span>other instances</span>
</div>
</div>
<div class='panel'>https://social.weho.st don't make use of advertising or external analytics software and does not make any money with your information.<br><br/> For more information on weho.st <a href="https://weho.st/faq" target="_blank"  style="color:#A0C6DA;">visit our FAQ</a>.

<div style="padding-top:2em;"></div>
<h3>Blocked servers</h3>

We have silenced the server <strong>pawoo.net</strong> due to a flood of images that are illegal in the US and EU. Their admin hasnt taken actions to moderate this content, if they do then we will consider removing the block.<br/><br/>

<i>We aim to not block instances unless they are serving illegal content under Dutch or EU laws. We do not enjoy or condone censorship but fulfil our legal requirements when necessary.</i>

<div style="padding-top:2em;"></div>
<h3>Rules</h3>

The following guidelines, mostly adopted from mastodon.social, are not a legal document, and final interpretation is up to the administrators of social.weho.st.
They are here to provide you with an insight into our content moderation policies:
<div style="padding-top:1em;"></div>
<ol>
  <li>
    The following types of content will be removed from the public timeline:
    <ol type="a">
      <li>Excessive advertising</li>
      <li>Untagged pornography and sexually explicit content</li>
      <li>Untagged gore and extremely graphic violence</li>
    </ol>
  </li>

  <li>
    The following types of content will be removed from the public timeline, and may result in account suspension and revocation of access to the service:
    <ol type="a">
      <li>Racism or advocation of racism</li>
      <li>Sexism or advocation of sexism</li>
      <li>Discrimination against gender and sexual minorities, or advocation thereof</li>
      <li>Xenophobic and/or violent nationalism</li>
    </ol>
  </li>

  <li>
    The following types of content are explicitly disallowed and will result in revocation of access to the service:
    <ol type="a">
      <li>Sexual depictions of children</li>
      <li>Content illegal in Germany and/or France, such as holocaust denial or Nazi symbolism</li>
      <li>Conduct promoting the ideology of National Socialism</li>
    </ol>
  </li>

  <li>
    Any conduct intended to stalk or harass other users, or to impede other users from utilizing the service, or to degrade the performance of the service, or to harass other users, or to incite other users to perform any of the aforementioned actions, is also disallowed, and subject to punishment up to and including revocation of access to the service. This includes, but is not limited to, the following behaviors:
    <ol type="a">
      <li>Continuing to engage in conversation with a user that has specifically has requested for said engagement with that user to cease and desist may be considered harassment, regardless of platform-specific privacy tools employed.</li>
      <li>Aggregating, posting, and/or disseminating a person's demographic, personal, or private data without express permission (informally called doxing or dropping dox) may be considered harassment.</li>
      <li>Inciting users to engage another user in continued interaction or discussion after a user has requested for said engagement with that user to cease and desist (informally called brigading or dogpiling) may be considered harassment.</li>
    </ol>
  </li>
<p>These provisions notwithstanding, the administration of the service reserves the right to revoke any user's access permissions, at any time, for any reason, except as limited by law.</p>
</ol></div>
</div>
<div class="sidebar">
<div class="panel">
<div class="panel-header">Contact</div>
<div class="panel-body">
</div>
</div>
<div class="panel">
<div class="panel-header">Links</div>
<div class="panel-list">
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>Contact</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="/system/accounts/avatars/000/000/002/original/52bd261ed98c4e98.jpg?1491583119" alt="52bd261ed98c4e98" /></div>
<div class='name'>
<a href="https://social.weho.st/@realitygaps"><span class='display_name emojify'>realitygaps</span>
<span class='username'>@realitygaps</span>
</a></div>
</div>
<div class='contact-email'>
Business e-mail:
<strong>hello AT weho DOT st</strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>Links</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></li>
</ul>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
