<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link color='#2B90D9' href='/mask-icon.svg' rel='mask-icon'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>toot.oekaki.st
 - toot.oekaki.st まったりお絵描き用</title>
<link rel="stylesheet" media="all" href="/assets/application-9f05ad922cfe8101e88e15d98470914c52e9abd25d84c6dbd270a7ae47ced160.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="ak35QAlXIN1AlJdrLNmqQ3vpnJBXzy/fRNceEf6Zo4/dm/MfY098Na0Ebb8vxaWFH8L4ucGm8DLjvhSaF/k+Bg==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>toot.oekaki.st</h2>
<p><p>まったり絵をアップできるお絵かきさん向けマストドンがほしいなあと思って作った小さなサーバー（インスタンス）です。ゆるゆるやっています。<br />
タイムラインの流れもそんなに速くないので、サブアカ用、おためし利用、絵のアップなどご自由にどうぞ。お気軽にご参加ください。</p>

<p><a href="http://k52.org/mastodon/?t=https://toot.oekaki.st" target="_blank">タイムラインのチラ見はこちら</a> ｜ <a href="https://toot.oekaki.st/about/more">サーバーの暫定ルールなどはこちら</a></p></p>
</div>
<div class='information-board'>
<div class='section'>
<span>ユーザー数</span>
<strong>272</strong>
<span>人</span>
</div>
<div class='section'>
<span>トゥート数</span>
<strong>2,884</strong>
<span>トゥート</span>
</div>
<div class='section'>
<span>接続中</span>
<strong>186</strong>
<span>個のインスタンス</span>
</div>
</div>
<div class='panel'><hr />

<h3>【暫定ルール】</h3>
<p>・エッチな絵・ポルノ絵は投稿しない</p>

<hr />

<p>I just opened this instance for the people who like oekaki (drawing & painting), especially for non-pornographic painters. This is a small and quiet instance yet, please feel free to join, toot and post your pictures.</p>

<h3>**temporary rules**</h3>
<p>Don't post any pictures containing sex & nudity.</p></div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>連絡先</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="/system/accounts/avatars/000/000/001/original/e9ad99a14275c75e.png?1492341274" alt="E9ad99a14275c75e" /></div>
<div class='name'>
<a href="https://toot.oekaki.st/@oekakist"><span class='display_name emojify'>oekaki.st🎨</span>
<span class='username'>@oekakist</span>
</a></div>
</div>
<div class='contact-email'>
ビジネスメールアドレス:
<strong></strong>
</div>
</div>
</div>

<div class='panel'>
<div class='panel-header'>リンク</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">参加する</a></li>
<li><a href="/auth/sign_in">ログイン</a></li>
<li><a href="/terms">プライバシーポリシー</a></li>
<li><a href="https://github.com/tootsuite/mastodon">ソースコード</a></li>
</ul>
</div>
</div>

</div>
</div>
</div>

</body>
</html>
