<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
<link href='/manifest.json' rel='manifest'>
<meta content='/browserconfig.xml' name='msapplication-config'>
<meta content='#282c37' name='theme-color'>
<meta content='yes' name='apple-mobile-web-app-capable'>
<title>woafre.tk
 - my123&#39;s Mastodon instance</title>
<link rel="stylesheet" media="all" href="/assets/application-c2a233c1f8ee2878ae4fec969dc5e50f1ef06fe1ec40ca2df60bdd58542badb1.css" />
<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="+Y0lGkJtiOczq9ARlGmmNF/OaqCzJZ6GEy54iVm9bSMtUjglkQcgE9N7u9rCNAcZOpjTlZn4N9Zw+bKOokdJJA==" />

</head>
<body class='about-body'>
<div class='wrapper thicc'>
<div class='sidebar-layout'>
<div class='main'>
<div class='panel'>
<h2>woafre.tk</h2>
</div>
<div class='information-board'>
<div class='section'>
<span>Home to</span>
<strong>14</strong>
<span>users</span>
</div>
<div class='section'>
<span>Who authored</span>
<strong>51</strong>
<span>statuses</span>
</div>
<div class='section'>
<span>Connected to</span>
<strong>173</strong>
<span>other instances</span>
</div>
</div>
</div>
<div class='sidebar'>
<div class='panel'>
<div class='panel-header'>Contact</div>
<div class='panel-body'>
<div class='owner'>
<div class='avatar'><img src="/system/accounts/avatars/000/000/001/original/c82cfe0a09dc4a04.jpg?1491649632" alt="C82cfe0a09dc4a04" /></div>
<div class='name'>
<a href="https://woafre.tk/@my123"><span class='display_name emojify'>my123 (@never_released) ✅</span>
<span class='username'>@my123</span>
</a></div>
</div>
</div>
</div>
<div class='panel'>
<div class='panel-header'>Links</div>
<div class='panel-list'>
<ul>
<li><a href="/auth/sign_up">Get started</a></li>
<li><a href="/auth/sign_in">Log in</a></li>
<li><a href="/terms">Terms</a></li>
<li><a href="https://github.com/tootsuite/mastodon">Source code</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>

</body>
</html>
